// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function FormatLastSeen(arg1) {
  return window['go']['main']['App']['FormatLastSeen'](arg1);
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetLights() {
  return window['go']['main']['App']['GetLights']();
}

export function GetRefreshInterval() {
  return window['go']['main']['App']['GetRefreshInterval']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function SetGroupLights(arg1, arg2) {
  return window['go']['main']['App']['SetGroupLights'](arg1, arg2);
}

export function SetGroupState(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetGroupState'](arg1, arg2, arg3);
}

export function SetLightState(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetLightState'](arg1, arg2, arg3);
}
