version: 2
updates:
  # Go modules dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "jmylchreest"
    assignees:
      - "jmylchreest"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "jmylchreest"
    assignees:
      - "jmylchreest"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
