version: 2

before:
  hooks:
    - go mod tidy
    - go mod vendor

builds:
  - id: keylightd
    main: ./cmd/keylightd
    binary: keylightd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}

  - id: keylightctl
    main: ./cmd/keylightctl
    binary: keylightctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}

release:
  disable: false
  extra_files:
    - glob: ./dist/gnome-extension/*.zip
      name_template: keylightd-control@jmylchreest.github.io.shell-extension.zip
    - glob: ./dist/keylightd-tray-artifact/*.tar.gz

archives:
  - id: default
    builds:
      - keylightd
      - keylightctl
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - contrib/systemd/keylightd.service

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

# homebrew_casks:
brews:
  - name: keylightd
    ids:
      - default
    description: "Daemon and CLI tool for managing HTTP-based Key Lights, including Elgato models"
    homepage: "https://github.com/jmylchreest/keylightd"
    license: "MIT"
    skip_upload: "{{ .IsSnapshot }}"
    repository:
      owner: jmylchreest
      name: homebrew-keylightd
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    # binary: |
    #   keylightd
    #   keylightctl

    install: |
      bin.install "keylightd"
      bin.install "keylightctl"

    service: |
      run bin/"keylightd"
      keep_alive true
      restart_delay 5
      process_type :background
      run_type :immediate

    test: |
      system "#{bin}/keylightd", "-h"
      system "#{bin}/keylightctl", "version"

    caveats: |
      keylightd daemon has been installed!

      To start keylightd manually:
        keylightd

      To start automatically with Homebrew services:
        brew services start keylightd

      To stop the service:
        brew services stop keylightd

      To restart the service:
        brew services restart keylightd

      To check service status:
        brew services list | grep keylightd

      Once started, control your lights with:
        keylightctl light list
        keylightctl --help

      Configuration will be created at: ~/.config/keylightd/
      Service logs will be written to: $(brew --prefix)/var/log/keylightd.log

aurs:
  - name: keylightd-bin
    ids:
      - default
    homepage: "https://github.com/jmylchreest/keylightd"
    description: "Daemon and CLI tool for managing HTTP-based Key Lights, including Elgato models"
    maintainers:
      - "{{ .Env.AUR_MAINTAINER }}"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/keylightd-bin.git"
    skip_upload: "{{ .IsSnapshot }}"
    provides:
      - keylightd
    conflicts:
      - keylightd
    package: |-
      # binaries
      install -Dm755 "./keylightd" "${pkgdir}/usr/bin/keylightd"
      install -Dm755 "./keylightctl" "${pkgdir}/usr/bin/keylightctl"

      # systemd service
      install -Dm644 "./contrib/systemd/keylightd.service" "${pkgdir}/usr/lib/systemd/system/keylightd.service"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/keylightd-bin/LICENSE"

      # documentation
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/keylightd-bin/README.md"

      # create keylightd user and group
      install -dm755 "${pkgdir}/usr/lib/sysusers.d"
      echo 'u keylightd - "Key Light Daemon" /var/lib/keylightd' > "${pkgdir}/usr/lib/sysusers.d/keylightd.conf"
      echo 'g keylightd -' >> "${pkgdir}/usr/lib/sysusers.d/keylightd.conf"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

  - name: keylightd-tray-bin
    ids: []
    url_template: "https://github.com/jmylchreest/keylightd/releases/download/{{ .Tag }}/keylightd-tray_{{ .Tag }}_linux_{{ .Arch }}.tar.gz"
    homepage: "https://github.com/jmylchreest/keylightd"
    goamd64: v1
    description: "System tray application for controlling Key Lights via keylightd"
    maintainers:
      - "{{ .Env.AUR_MAINTAINER }}"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/keylightd-tray-bin.git"
    skip_upload: "{{ .IsSnapshot }}"
    depends:
      - gtk3
      - webkit2gtk-4.1
    optdepends:
      - "keylightd: for local socket connection"
    provides:
      - keylightd-tray
    conflicts:
      - keylightd-tray
    package: |-
      # binary
      install -Dm755 "./keylightd-tray" "${pkgdir}/usr/bin/keylightd-tray"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/keylightd-tray-bin/LICENSE"

      # documentation
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/keylightd-tray-bin/README.md"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
