version: 2

before:
  hooks:
    - go mod tidy
    - go mod vendor

builds:
  - id: keylightd
    main: ./cmd/keylightd
    binary: keylightd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}

  - id: keylightctl
    main: ./cmd/keylightctl
    binary: keylightctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}

release:
  disable: false
  extra_files:
    - glob: ./dist/gnome-extension/*.zip
      name_template: keylightd-control@jmylchreest.github.io.shell-extension.zip

archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

brews:
  - name: keylightd
    description: "Daemon and CLI tool for managing Elgato Key Lights on your local network"
    homepage: "https://github.com/jmylchreest/keylightd"
    license: "MIT"
    repository:
      owner: jmylchreest
      name: homebrew-keylightd
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "keylightd"
      bin.install "keylightctl"
    test: |
      system "#{bin}/keylightd", "-h"
      system "#{bin}/keylightctl", "version"
    skip_upload: "{{ .IsSnapshot }}"
