site_name: keylightd API Documentation
site_description: Documentation for the keylightd API for HTTP-based Key Light devices, including Elgato models.
site_author: keylightd Team
docs_dir: docs

theme:
  name: material
  # custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html

extra_javascript:
  - https://unpkg.com/swagger-ui-dist@latest/swagger-ui-bundle.js

extra_css:
  - https://unpkg.com/swagger-ui-dist@latest/swagger-ui.css
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Screenshots:
      - Gnome Extension: screenshots/gnome-extension.md
  - Supported Devices:
      - Overview: supported-devices/index.md
      - Elgato Key Light Series: supported-devices/elgato.md
  - Lights:
      - CLI: lights/cli.md
      - HTTP API: lights/http.md
      - Socket API: lights/socket.md
  - Groups:
      - CLI: groups/cli.md
      - HTTP API: groups/http.md
      - Socket API: groups/socket.md
  - API Reference:
      - HTTP REST API: api/index.md
      - Unix Socket API: socket-api.md
