// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateGroup(arg1:string):Promise<void>;

export function DeleteGroup(arg1:string):Promise<void>;

export function FormatLastSeen(arg1:number):Promise<string>;

export function GetCustomCSS():Promise<string>;

export function GetGroups():Promise<Array<main.Group>>;

export function GetLights():Promise<Array<main.Light>>;

export function GetRefreshInterval():Promise<number>;

export function GetSettings():Promise<main.Settings>;

export function GetStatus():Promise<main.Status>;

export function GetVersion():Promise<string>;

export function HideWindow():Promise<void>;

export function Ping():Promise<void>;

export function Quit():Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SetCustomCSSPath(arg1:string):Promise<void>;

export function SetGroupLights(arg1:string,arg2:Array<string>):Promise<void>;

export function SetGroupState(arg1:string,arg2:string,arg3:any):Promise<void>;

export function SetInitialWindowHeight(arg1:number):Promise<void>;

export function SetLightState(arg1:string,arg2:string,arg3:any):Promise<void>;

export function SetTrayManager(arg1:main.TrayManager):Promise<void>;

export function ShowWindow():Promise<void>;
